name: CICD

on:
  push:
    branches: [ main ]
    tags: [v*]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  make-distcheck:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'CLI: sudo apt install build-dependencies'
        run: sudo apt install
          autotools-dev
          zlib1g-dev
          libice-dev
          libsm-dev
          libxext-dev
          libxdamage-dev
          libogg-dev
          libvorbis-dev
          libtheora-dev
          libjack-jackd2-dev
          libasound2-dev
          libpopt-dev

      - name: 'CLI: sh autogen.sh'
        run: cd recordmydesktop ; sh autogen.sh

      - name: 'CLI: ./configure --prefix /tmp/recordmydesktop-prefix'
        run: cd recordmydesktop ; ./configure --prefix /tmp/recordmydesktop-prefix

      - name: 'CLI: make distcheck'
        run: cd recordmydesktop ; AM_CFLAGS=-Werror make distcheck

      - name: 'CLI: figure out tarball name'
        id: tarball-name
        run: |
          cd recordmydesktop
          TARBALL_NAME=$(echo recordmydesktop-*.tar.gz)
          echo ::set-output name=TARBALL_NAME::${TARBALL_NAME}

      - name: 'CLI: publish tarball artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.tarball-name.outputs.TARBALL_NAME }}
          path: recordmydesktop/${{ steps.tarball-name.outputs.TARBALL_NAME }}

      - name: 'CLI: create release'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            recordmydesktop/${{ steps.tarball-name.outputs.TARBALL_NAME }}

      - name: 'GTK: sudo apt install build-dependencies'
        run: sudo apt install
          gettext
          python3-gi
          python3-gi-cairo
          gir1.2-gtk-3.0

      - name: 'GTK: sh autogen.sh'
        run: cd gtk-recordmydesktop ; sh autogen.sh

      - name: 'GTK: ./configure --prefix /tmp/recordmydesktop-prefix'
        run: cd gtk-recordmydesktop ; ./configure --prefix /tmp/recordmydesktop-prefix

      - name: 'GTK: make'
        run: cd gtk-recordmydesktop ; AM_CFLAGS=-Werror make

      - name: 'GTK: make install'
        run: cd gtk-recordmydesktop ; make install
