name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  configure-make-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: sudo apt install build-dependencies
        run: sudo apt install \
          autoconf \
          automake \
          libtool \
          libz-dev \
          libpopt-dev \
          libpopt-dev \
          libice-dev \
          libsm-dev \
          libx11-dev \
          libxext-dev \
          libxfixes-dev \
          libxdamage-dev \
          libvorbis-dev \
          libtheora-dev \
          libjack-dev

      - name: sh autogen.sh
        run: cd recordmydesktop ; sh autogen.sh

      - name: ./configure --prefix /tmp/recordmydesktop-prefix
        run: cd recordmydesktop ; ./configure --prefix /tmp/recordmydesktop-prefix

      - name: make
        run: cd recordmydesktop ; make

      - name: make install
        run: cd recordmydesktop ; make install
